sudo: required

language: generic

services:
  - docker

before_install:
  - source version.sh
  - echo $VERSION
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -f latest/Dockerfile -t bludoc/node-red .
  - docker build -f latest/Dockerfile -t bludoc/node-red:v10 --build-arg NODE_VERSION=10 .
  - docker tag nodered/node-red-docker bludoc/node-red:v8
  - docker tag nodered/node-red-docker bludoc/node-red:$VERSION-v8
  - docker tag nodered/node-red-docker:v10 bludoc/node-red:$VERSION-v10
  - docker tag nodered/node-red-docker bludoc/node-red:$VERSION

script:
  - docker run -d bludoc/node-red:latest
  - docker ps | grep latest
  - docker run -d bludoc/node-red:v10
  - docker ps | grep v10
  - docker run -d bludoc/node-red:v8
  - docker ps | grep v8

after_success:
  - if [ -n "$TRAVIS_TAG" ]; then
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push bludoc/node-red;
    fi
