# Python CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
# This is mainly taken from
# https://vsupalov.com/build-docker-image-with-circle-ci-2-push-to-google-container-registry/
# and adapted to our needs. Thanks for the awesome preparation.
version: 2.1
workflows:
  build_and_push:
    jobs:
      - build:
          context: Docker bludoc

jobs:
  build:
    docker:
      - image: circleci/node:8

    working_directory: ~/repo

    steps:
      - checkout

      # This builds the image and uploads it to hub.docker.com. Taken from
      # https://circleci.com/docs/2.0/building-docker-images/#overview
      - setup_remote_docker

      # Build image.
      - run:
          name: Build image
          command: |
            source version.sh
            echo $VERSION
            docker run --rm --privileged multiarch/qemu-user-static:register --reset
            docker build -f latest/Dockerfile -t bludoc/node-red .
            docker build -f latest/Dockerfile -t bludoc/node-red:v10 --build-arg NODE_VERSION=10 .
            docker tag nodered/node-red-docker bludoc/node-red:v8
            docker tag nodered/node-red-docker bludoc/node-red:$VERSION-v8
            docker tag nodered/node-red-docker:v10 bludoc/node-red:$VERSION-v10
            docker tag nodered/node-red-docker bludoc/node-red:$VERSION

      # Test images.
      - run:
          name: Test images
          command: |
            docker run -d bludoc/node-red:latest
            docker ps | grep latest
            docker run -d bludoc/node-red:v10
            docker ps | grep v10
            docker run -d bludoc/node-red:v8
            docker ps | grep v8


      # Push image.
      - run:
          name: Push image
          command: |
            echo $DOCKER_PASS | docker login \
              --username $DOCKER_USER --password-stdin
            docker push bludoc/node-red
